config/routes.rb
Rails.application.routes.draw do
  
  

 

use_doorkeeper
devise_for :users, :controllers => { registrations: 'users/registrations' }
resources :wedding_guests

devise_scope :user do
  get 'register', to: 'users/registrations#new', as: :register
  get 'register_wedding', to: 'users/registrations#new', as: :register_wedding
  get '/login', to: 'users/sessions#new', as: :login
  get '/logout', to: 'users/sessions#destroy', as: :logout
  resources :wedding_guests

end

authenticated :user, lambda {|u| u.admin == true} do
  root to: "weddings#index", as: :user_root
  get 'weddings/search_results', to: 'weddings#search_results'
  get 'weddings/add_wedding', to: 'weddings#add_wedding'
  resources :wedding_guests

  resources :weddings do
  
  resources :pins do
    member do
      put "like", to: "pins#upvote"
    end
  end 
    resources :guest_lists
    resources :venues 
    resources :galleries 
  resources :pictures
  resources :content
  end

end

authenticated :user, lambda {|u| u.admin == false} do
  root to: "weddings#index", as: :user_visitor
  get 'weddings/search_results', to: 'weddings#search_results'
  get 'weddings', to: 'weddings#index'
  resources :weddings, only: [:show, :search_results] do
    resources :pins do
    member do
      put "like", to: "pins#upvote"
    end
end 
  resources :venues, only: [:show, :index]
  resources :galleries, only: [:show, :index]
  resources :pictures, only: [:show, :index]
  
end
end

  
root to: 'welcome#index'
resources :welcome

namespace :api do
namespace :v1 do
  get 'items/create'
  end
end

namespace :api do
    namespace :v1 do
    resources :weddings
  end
end

  

end

app/models/venue.rb
class Venue < ActiveRecord::Base
  belongs_to :wedding
  validates :name, presence: true,
				     length: {minimum: 3}
	validates :description, presence: true,
				     length: {minimum: 3}
 	validates :street, presence: true,
				     length: {minimum: 3}
	validates :city, presence: true,
				     length: {minimum: 3}
	validates :zip, presence: true,
				     length: {minimum: 3}

	validates :state, presence: true,
				     length: {minimum: 3}
	validates :url, presence: true,
				     length: {minimum: 3}
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  
  before_action :find_wedding
  before_action :set_venue, only: [:edit, :update]

  def update
    respond_to do |format|
      if @venue.update(venue_params)
        format.html { redirect_to @wedding, notice: 'Venue was successfully updated.' }
        format.json { render :show, status: :ok, location: @venue }
      else
        format.html { render :edit }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  def show

  end

def destroy
  if @wedding.venues.first.destroy
  respond_to do |format|
      format.html { redirect_to weddings_url, notice: 'Venue was successfully destroyed.' }
      format.json { head :no_content }
    end
  else
    respond_to do |format|
      format.html { redirect_to weddings_url, notice: 'Venue was not destroyed.' }
      format.json { head :no_content }
    end

end
end

  def edit
    @venue = @wedding.venues.first
  end

  def new
  	@venue = @wedding.venues.new
  end

  def create
   
   @venue = @wedding.venues.new(venue_params)
    if @venue.save
      flash[:success] = "Added venue to wedding."
      redirect_to wedding_venues_path(@wedding)
    else
      flash[:error] = "there was a problem adding venue to wedding."
      render action: :new
    end
  end

  private

  def find_wedding
  	@wedding = current_user.wedding
  end

def venue_params
      params[:venue].permit(:name, :description, :street, :city, :zip, :state, :url)
    end


    def set_venue
 @venue = current_user.wedding.venues.find(params[:id])
    end


end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/_form.html.erb
<%= simple_form_for([@wedding, @venue], html: {class: "well"}) do |f| %> 
 <% if @venue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@venue.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

      <ul>
      <% @venue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="name">
  <%= f.input :name %><br>
  
  </div>

  <div class="description">
   <%= f.input :description %><br>
  
  </div>

  <div class="street">
 <%= f.input :street %><br>
  </div>

<div class="city">
 <%= f.input :city %><br>
  </div>

<div class="zip">
<%= f.input :zip %><br>
  </div>

<div class="state">
   <%= f.input :state %><br>
  </div>

<div class="url">
   <%= f.input :url %><br>
  </div>


  <div class="action">  
  <%= f.button :submit %>
  </div>
   
<% end %>

app/views/venues/edit.html.erb
<h1>Editing wedding</h1>
<div class = "row">
  <div class = "col-md-4">
  

<%= render partial: 'form' %>


<%= link_to 'Show', @wedding_venues_path %> |
<%= link_to 'Back', weddings_path %>

</div>
</div>

app/views/venues/index.html.erb
 <!-- main right col -->
            <div class="column col-sm-10 col-xs-11" id="main">
                
               
              
                <div class="padding">
                    <div class="full col-sm-9">
                      
                        <!-- content -->                      
                        <div class="row">
                          
                         <!-- main col left --> 
                         <div class="panel panel-default">
                                <div class="panel-heading"> Venue
                                </div>
                                <div class="panel-body">

        <p>
          <strong>Venue</strong>
        </p>
      </div>
        
      
        <% if @wedding.venues.blank? %>
        

         
          <%= link_to "Create a Venue", new_wedding_venue_path(@wedding), class: "btn btn-info" if current_user.admin%> 
       </div>

        <%else %>

        <div class="panel-body">

          <% @wedding.venues.reload %>
          <p>
          <strong>Name:</strong>
          <%= @wedding.venues.first.name %>
          </p>

          <p>
          <strong>Description:</strong>
          <%= @wedding.venues.first.description %>
          </p>

          <p>
          <strong>Street:</strong>
          <%= @wedding.venues.first.street %>
          </p>

          <p>
          <strong>City:</strong>
          <%= @wedding.venues.first.city %>
          </p>


          <p>
          <strong>Zip:</strong>
          <%= @wedding.venues.first.zip %>
          </p>

          <p>
          <strong>State:</strong>
          <%= @wedding.venues.first.state %>
          </p>

          <p>
          <strong>URL:</strong>
          <%= @wedding.venues.first.url %>
          </p>
        </div>
        <div class="panel-footer">

        <%= link_to 'Edit', edit_wedding_venue_path(@wedding, @wedding.venues.first) %> 
        <%= link_to 'Back', weddings_path %>
        <%= link_to 'Delete', wedding_venue_path(@wedding, @wedding.venues.first), method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>

        
       <%end%>

  </div>
</div>
</div>

app/views/venues/new.html.erb
<h1><%= @wedding.name %> </h1>
 <div class = "row">
  <div class = "col-md-4">
  
  <%= render 'form' %>


 

</div>
  </div>