config/routes.rb
Rails.application.routes.draw do
  
  

 

use_doorkeeper
devise_for :users, :controllers => { registrations: 'users/registrations' }
resources :wedding_guests

devise_scope :user do
  get 'register', to: 'users/registrations#new', as: :register
  get 'register_wedding', to: 'users/registrations#new', as: :register_wedding
  get '/login', to: 'users/sessions#new', as: :login
  get '/logout', to: 'users/sessions#destroy', as: :logout
  resources :wedding_guests

end

authenticated :user, lambda {|u| u.admin == true} do
  root to: "weddings#index", as: :user_root
  get 'weddings/search_results', to: 'weddings#search_results'
  get 'weddings/add_wedding', to: 'weddings#add_wedding'
  resources :wedding_guests

  resources :weddings do
  
  resources :pins do
    member do
      put "like", to: "pins#upvote"
    end
  end 
    resources :guest_lists
    resources :venues 
    resources :galleries 
  resources :pictures
  resources :content
  end

end

authenticated :user, lambda {|u| u.admin == false} do
  root to: "weddings#index", as: :user_visitor
  get 'weddings/search_results', to: 'weddings#search_results'
  get 'weddings', to: 'weddings#index'
  resources :weddings, only: [:show, :search_results] do
    resources :pins do
    member do
      put "like", to: "pins#upvote"
    end
end 
  resources :venues, only: [:show, :index]
  resources :galleries, only: [:show, :index]
  resources :pictures, only: [:show, :index]
  
end
end

  
root to: 'welcome#index'
resources :welcome

namespace :api do
namespace :v1 do
  get 'items/create'
  end
end

namespace :api do
    namespace :v1 do
    resources :weddings
  end
end

  

end

app/models/wedding.rb
class Wedding < ActiveRecord::Base
	has_many :venues
	has_many :pins
	has_many :galleries
	belongs_to :user
	#belongs_to :owner, class_name: "User", foreign_key: "user_id"
	#has_many :guests, class_name: "User", foreign_key: "guest_id"
	has_many :wedding_guests
	has_many :guests, through: :wedding_guests
	has_one :content
	has_many :guest_lists
	

	#belongs_to :admin
	

	#accepts_nested_attributes_for :content
	


	validates :name, presence: true,
				     length: {minimum: 3}

	def self.search(query)
		where("name like ?", "%#{query}%") 
	end


	def self.guests(wedding, user)
		wedding.wedding_guests.where(user_id: user)
	end





	

		


end

app/controllers/api/v1/weddings_controller.rb
module API
  module V1
  class WeddingsController < API::V1::BaseController
  
 
 


    

  

private
     def wedding_params
      params.require(:wedding).permit(:name, :bride, :groom, :date)
    end

      def query_params
        # this assumes that an album belongs to an artist and has an :artist_id
        # allowing us to filter by this
        params.permit(:name)
      end

     end
  end
end
  


  

app/controllers/weddings_controller.rb
class WeddingsController < ApplicationController
  #before_action :set_wedding
  before_filter :authenticate_user!
  before_action :wedding_layout
 # layout :layout_by_resource
  #layout :wedding_layout
  # GET /weddings
  # GET /weddings.json



  def index
  if current_user.admin
    @weddings = current_user.wedding 
  else
    @weddings = current_user.wedding_part
  end
  
 
  
  
  
  end

  def search_results
    if params[:search]
      @weddings = Wedding.search(params[:search]).order("created_at DESC")
    else
      @weddings = Wedding.order("created_at DESC")
    end
  end

  

  

  # GET /weddings/1
  # GET /weddings/1.json
  def show
    
    @wedding = Wedding.find(params[:id])
    render layout: 'show'
end

  # GET /weddings/new
  def new
    @wedding = Wedding.new
    
  end

  # GET /weddings/1/edit
  def edit
    
    #@wedding.build_document
  end

  # POST /weddings
  # POST /weddings.json
  def create

    
    @wedding = current_user.build_wedding(wedding_params)
  
    respond_to do |format|
      if @wedding.save
        format.html { redirect_to @wedding, notice: 'Wedding was successfully created.' }
        format.json { render :show, status: :created, location: @wedding }
        
      else
        format.html { render :new }
        format.json { render json: @wedding.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weddings/1
  # PATCH/PUT /weddings/1.json
  def update
    respond_to do |format|
      if @wedding.update(wedding_params)
        format.html { redirect_to @wedding, notice: 'Wedding was successfully updated.' }
        format.json { render :show, status: :ok, location: @wedding }
         format.json { render :show, status: :created, location: @wedding }
        if params[:pictures]
          params[:pictures].each { |picture|
            @wedding.site_contents.create(picture: picture)
          }
        end
      else
        format.html { render :edit }
        format.json { render json: @wedding.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weddings/1
  # DELETE /weddings/1.json
  def destroy
    @wedding.destroy
    respond_to do |format|
      format.html { redirect_to weddings_url, notice: 'Wedding was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wedding
      @wedding = Wedding.find(params[:id]) if params[:id]
    end

    


    # Never trust parameters from the scary internet, only allow the white list through.
    def wedding_params
      params.require(:wedding).permit(:name, :bride, :groom, :date) 
    end

  

    def wedding_layout
      if current_user.admin?
       @wedding = Wedding.find(params[:id]) if params[:id]
      "application"
    else
       @wedding = Wedding.find(params[:id]) if params[:id]
       "wedding_view"
    end
  
end

end

app/helpers/weddings_helper.rb
module WeddingsHelper
end

app/views/weddings/_form.html.erb
<%= simple_form_for @wedding, html: {class: "form-horizontal", :multipart => true} do |f| %>
  <% if @wedding.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wedding.errors.count, "error") %> prohibited this wedding from being saved:</h2>

      <ul>
      <% @wedding.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



    <legend>Wedding Picture</legend>





    <legend>About My Wedding</legend>
  <div class="field">
    <%= f.input :name %><br>
    
 
    <%= f.input :bride %><br>
    

    <%= f.input :groom %><br>
    
 
    <%= f.input_field :date, as: :date %><br>


    
  </div>
  


  
  
    <%= f.button :submit %>
  
<% end %>

app/views/weddings/_gallery.html.erb
   <ul class="thumbnails files">
    <% @wedding.galleries.each do |gallery| %>
        <li class="span4" id="gallery_<%= gallery.id %>">
          <div class="thumbnail">
            <% if gallery.pictures.first %>
            <%= link_to image_tag(gallery.pictures.first.image.url(:thumb)), wedding_gallery_path(@wedding, gallery) %>
            <% else %>
              N/A
            <% end %>
            <div class="caption">
              <p style="text-align: center;">
                <%= gallery.name.truncate(14) %>
                <%= link_to "Show", wedding_gallery_path(@wedding, gallery) %>

                </p>
            </div>
                    <% unless gallery.pictures.empty? %>
                    <div id="links"><left> 

                    <% gallery.pictures.each do |pic| %>
    
                      <%= link_to(image_tag(pic.image.url(:thumb)) , pic.image.url) %>
                    <% end %> 
                    </left></div>
                  <% end %>
                <% end %>
              
          </div>
        </li>
   


    
  </ul>

app/views/weddings/display.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Welcome to <% @wedding.name %></title>
</head>
<body>

</body>
</html>

app/views/weddings/edit.html.erb
<h1>Editing wedding</h1>
<div class = "row">
  <div class = "col-md-4">
  

<%= render 'form' %>


<%= link_to 'Show', @wedding %> |
<%= link_to 'Back', weddings_path %>

</div>
</div>

app/views/weddings/index.html.erb
          
            <!-- main right col -->
            <div class="column col-sm-10 col-xs-11" id="main">
                
               
              
                <div class="padding">
                    <div class="full col-sm-9">
                      
                        <!-- content -->                      
                        <div class="row">
                          
                         <!-- main col left --> 
                         <div class="panel panel-default">
                                <div class="panel-heading"> Wedding List
                                </div>
                                <div class="panel-body">
                        
                         <%= div_for(@weddings, class: "starter-template") do |wedding| %>
                         <div class="<%= cycle('oddrow', 'evenrow') -%>">
                            <tr>
                              

                            
                              <td><%= wedding.name %></td>
                              <td><%= wedding.bride %></td>
                              <td><%= wedding.groom %></td>
                              <td><%= wedding.date %></td>
                              <td><%= link_to 'Show', wedding %></td>
                              <td><%= link_to "Pins", wedding_pins_path(wedding)%></td>
                              <td><%= link_to "Galleries", wedding_galleries_path(wedding)%></td>

                              <% if current_user.admin %>
                              <td><%= link_to 'Edit', edit_wedding_path(wedding) %></td>
                              <td><%= link_to 'Destroy', wedding, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                            </tr>
                        </div>
                          <% end  %>
                           <% end %>
                        <br><%= link_to 'New Wedding', new_wedding_path, class: "btn btn-info" if current_user.admin%>
                              
                         
                          <%= form_tag(weddings_search_results_path, :method => "get", class: "navbar-form", id: "search-form") do %>
                          
                         
                            <div class="input-append">
                              <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Search Weddings" %>
                              <!-- In order to have the "search" icon int the button, we need to use plain HTML instead 
                                   of using a Rails form helper -->
                              <%= link_to("Search", weddings_search_results_path, class: "btn btn-info") %>
                            </div>

                          </div>
                          <% end %>

                          
                          </div>

                          <div class="panel panel-default">
                                <div class="panel-heading"> Weddings
                                </div>
                                <div class="panel-body">
                        
                         
                         

                           
                             
                          
                          <!-- main col right -->
                          <div class="col-sm-7">
                               
                                
                        
                      
                    </div><!-- /col-9 -->
                </div><!-- /padding -->
            </div>
            <!-- /main -->
          
        </div>
    </div>
</div>

app/views/weddings/new.html.erb
<h1>New Wedding</h1>
   <div class = "row">
  <div class = "col-md-4">

<%= render 'form' %>

</div>
</div>


<%= link_to 'Back', weddings_path %>

app/views/weddings/search_results.html.erb


  <% @weddings.each do |wedding| %>
  <div class="wedding">
    <h1 class="wedding-name"><%= link_to wedding.name, wedding %></h1>
    <p class="wedding-bride"><%= wedding.bride %></p>
    <%= link_to "Add Wedding", wedding_guests_path(guest_id: current_user.id, wedding_id: wedding.id), class: 'btn btn-primary', data: { guest_id: current_user.id, wedding_id: wedding.id}, method: :post %>


  </div>
<% end %>

app/views/weddings/show_back.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<div class="row">
  <div class="col-md-4">
    <div class="panel panel-primary">
      <div class="panel-heading">

      
     
        <%= wedding_document_link(@wedding) %>

        <p> 
          <strong>Name:</strong> 
          <%= @wedding.name %>
        </p>
      
      </div>
        
      <div class="panel-body">
        <p>
          <strong>Bride:</strong>
          <%= @wedding.bride %>
        </p>

        <p>
          <strong>Groom:</strong>
          <%= @wedding.groom %>
        </p>

        <p>
          <strong>Date:</strong>
          <%= @wedding.date %>
        </p>
      </div>
        
      <div class="panel-footer">

        <%= link_to 'Edit', edit_wedding_path(@wedding) %> |
        <%= link_to 'Back', weddings_path %>
      </div>
       
    </div>
  </div>


  <div= class="col-md-4">
    <div class="panel panel-primary">
      <div class="panel-heading">

        <p>
          <strong>Venue</strong>
        </p>
      </div>
        
      
        <% if @wedding.venues.blank? %>
        <div class="panel-footer">

         <strong>New:</strong>
          <%= link_to "Create a Venue", new_wedding_venue_path(@wedding) %>
       </div>

        <%else %>

        <div class="panel-body">

          <% @wedding.venues.reload %>
          <p>
          <strong>Name:</strong>
          <%= @wedding.venues.first.name %>
          </p>

          <p>
          <strong>Description:</strong>
          <%= @wedding.venues.first.description %>
          </p>

          <p>
          <strong>Street:</strong>
          <%= @wedding.venues.first.street %>
          </p>

          <p>
          <strong>City:</strong>
          <%= @wedding.venues.first.city %>
          </p>


          <p>
          <strong>Zip:</strong>
          <%= @wedding.venues.first.zip %>
          </p>

          <p>
          <strong>State:</strong>
          <%= @wedding.venues.first.state %>
          </p>

          <p>
          <strong>URL:</strong>
          <%= @wedding.venues.first.url %>
          </p>
        </div>
        <div class="panel-footer">

        <%= link_to 'Edit', edit_wedding_venue_path(@wedding, @wedding.venues.first) %> 
        <%= link_to 'Back', weddings_path %>
      </div>

        
       <%end%>

  </div>
</div>
</div>

app/views/weddings/wedding_view.html.erb

 <!DOCTYPE html>
<html>
<head>
	<title>Chrisbook</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top" id="top"role="navigation">
  
  <div class="container">
    <div class = "navbar-header">
    
    <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        
      </button>
      
      <a href="../" class="navbar-brand">ChrisBook</a>
    </div>

    <nav class="navbar-collapse bs-navbar-collapse collapse in" aria-expanded="true">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "weddings", weddings_path %>
        </li>
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if admin_signed_in? %>
        
        
 
 <li><%= link_to current_admin, edit_admin_registration_path %> </li>
  <li><%= link_to "Log Out", logout_path %></li>
  <% else %>
  <li><%= link_to "Register", register_path %> </li> 

   <li><%= link_to "Log in", login_path %> </li> 
  <%end%>
  </ul>
     </div>
    </nav>
     
 
	<div class="container">
    <%flash.each do |type, message| %>
    
    <div class="alert <%= flash_class type %> alert-dismissible " role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= message %>

    </div>
  

    <% end %>  

       

    <%= yield %>
    </div>
   <%= params.inspect %>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>

		

	
