config/routes.rb
Rails.application.routes.draw do
  
  

 

use_doorkeeper
devise_for :users, :controllers => { registrations: 'users/registrations' }
resources :wedding_guests

devise_scope :user do
  get 'register', to: 'users/registrations#new', as: :register
  get 'register_wedding', to: 'users/registrations#new', as: :register_wedding
  get '/login', to: 'users/sessions#new', as: :login
  get '/logout', to: 'users/sessions#destroy', as: :logout
  resources :wedding_guests

end

authenticated :user, lambda {|u| u.admin == true} do
  root to: "weddings#index", as: :user_root
  get 'weddings/search_results', to: 'weddings#search_results'
  get 'weddings/add_wedding', to: 'weddings#add_wedding'
  resources :wedding_guests

  resources :weddings do
  
  resources :pins do
    member do
      put "like", to: "pins#upvote"
    end
  end 
    resources :guest_lists
    resources :venues 
    resources :galleries 
  resources :pictures
  resources :content
  end

end

authenticated :user, lambda {|u| u.admin == false} do
  root to: "weddings#index", as: :user_visitor
  get 'weddings/search_results', to: 'weddings#search_results'
  get 'weddings', to: 'weddings#index'
  resources :weddings, only: [:show, :search_results] do
    resources :pins do
    member do
      put "like", to: "pins#upvote"
    end
end 
  resources :venues, only: [:show, :index]
  resources :galleries, only: [:show, :index]
  resources :pictures, only: [:show, :index]
  
end
end

  
root to: 'welcome#index'
resources :welcome

namespace :api do
namespace :v1 do
  get 'items/create'
  end
end

namespace :api do
    namespace :v1 do
    resources :weddings
  end
end

  

end

app/views/layouts/application.html.erb
 
<!DOCTYPE html>
<html lang="en">
  <head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>WeddingApp</title>
    <meta name="generator" content="Bootply" >
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
   
    <!--[if lt IE 9]>
      <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    
   
  </head>
  <body>
<div class="navbar navbar-default navbar-fixed-top">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">WeddingApp</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'Wedding', weddings_path %></li>
           
        
          <li><%= link_to current_user.full_name, edit_user_registration_path %> </li>
          <li><%= link_to "Log Out", logout_path %></li>
       <% else %>
          <li><%= link_to "Register", register_path %> </li> 

          <li><%= link_to "Log in", login_path %> </li> 
       <%end%>
      </ul>
    </div><!--/.nav-collapse -->
</div><!--/.navbar -->

<div class="row-offcanvas row-offcanvas-left">
  <div id="sidebar" class="sidebar-offcanvas">
      <div class="col-md-12">
        
        <ul class="nav nav-pills nav-stacked">
          
          <li><%= link_to "Home", weddings_path %></li>
          <li> <%= link_to 'Wedding', edit_wedding_path(current_user.wedding) if current_user.wedding%></li>
          <li> <%= link_to "Venue", wedding_venues_path(current_user.wedding) if current_user.wedding%></li>
          <li> <%= link_to "Pins", wedding_pins_path(current_user.wedding) if current_user.wedding%></li>
          <li> <%= link_to "Gallery", wedding_galleries_path(current_user.wedding) if current_user.wedding%></li>
          <li> <%= link_to "Content", wedding_content_index_path(current_user.wedding) if current_user.wedding%></li>
          <li> <%= link_to "Guest List", wedding_guest_lists_path(current_user.wedding) if current_user.wedding%></li>

        </ul>
      </div>
  </div>
  <div id="main">
      <div class="col-md-12">
          <p class="visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas"><i class="glyphicon glyphicon-chevron-left"></i></button>
          </p>
           <% if notice %>
              <p class="alert alert-success"><%= notice %></p>
           <% end %>
           <% if alert %>
              <p class="alert alert-danger"><%= alert %></p>
            <% end %>
          <%= yield %>
            <%= debug(params) if Rails.env.development? %>
      </div>
  </div>
  </div>
  </body>
</div><!--/row-offcanvas -->
  

app/views/layouts/show.html.erb

<%= yield %>


app/views/layouts/wedding_view.html.erb

<!DOCTYPE html>
<html lang="en">
  <head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>WeddingApp</title>
    <meta name="generator" content="Bootply" >
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
   
    <!--[if lt IE 9]>
      <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    
    </head>
  <body>
<div class="navbar navbar-default navbar-fixed-top">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">WeddingApp</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'Wedding', weddings_path %></li>
          
        
          <li><%= link_to current_user.full_name, edit_user_registration_path %> </li>
          <li><%= link_to "Log Out", logout_path %></li>
       <% else %>
          <li><%= link_to "Register", register_path %> </li> 

          <li><%= link_to "Log in", login_path %> </li> 
       <%end%>
      </ul>
    </div><!--/.nav-collapse -->
</div><!--/.navbar -->

<div id="main">
      <div class="col-md-12">
          
           <% if notice %>
              <p class="alert alert-success"><%= notice %></p>
           <% end %>
           <% if alert %>
              <p class="alert alert-danger"><%= alert %></p>
            <% end %>
          <%= yield %>
            <%= debug(params) if Rails.env.development? %>
      </div>
  </div>
  </div>
  </body>